services:
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}:${IMAGE_TAG}
    container_name: imgproc-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${HOST_HTTP_PORT}:3000"
    volumes:
      - /srv/imgproc/storage/outputs:/app/storage/outputs
      - /srv/imgproc/storage/data:/app/storage/data
